import numpy as np

print('🎵 COMPLETE MOOD RANGES - MODEL + HEURISTIC SYSTEM')
print('=' * 60)

# Feature normalization formulas
print('\n📊 FEATURE NORMALIZATION (0-1 SCALE):')
print('-' * 40)

print('🎶 TEMPO SCORE:')
print('  Formula: tempo_score = np.clip(tempo / 140.0, 0, 1)')
print('  Range: 0 BPM → 0, 140+ BPM → 1')
print('  0.0 = 0 BPM (very slow)')
print('  0.5 = 70 BPM (moderate)')
print('  0.7 = 98 BPM (fast)')
print('  1.0 = 140+ BPM (very fast)')

print('\n⚡ ENERGY SCORE:')
print('  Formula: energy_score = np.clip(energy / 0.3, 0, 1)')
print('  Range: 0 RMS → 0, 0.3+ RMS → 1')
print('  0.0 = 0 RMS (silent)')
print('  0.3 = 0.09 RMS (low)')
print('  0.4 = 0.12 RMS (moderate)')
print('  0.5 = 0.15 RMS (high)')
print('  1.0 = 0.3+ RMS (very loud)')

print('\n🌟 BRIGHTNESS SCORE:')
print('  Formula: brightness_score = np.clip(spectral_centroid / 3000.0, 0, 1)')
print('  Range: 0 Hz → 0, 3000+ Hz → 1')
print('  0.0 = 0 Hz (very dark)')
print('  0.6 = 1800 Hz (bright)')
print('  1.0 = 3000+ Hz (very bright)')

print('\n🥁 RHYTHMIC SCORE:')
print('  Formula: rhythmic_score = np.clip(onset / 2.0, 0, 1)')
print('  Range: 0 onset → 0, 2.0+ onset → 1')
print('  0.0 = No rhythmic activity')
print('  0.5 = Moderate rhythmic complexity')
print('  1.0 = High rhythmic complexity')

print('\n🎼 HARMONIC SCORE:')
print('  Formula: harmonic_score = np.clip(chroma / 0.5, 0, 1)')
print('  Range: 0 chroma → 0, 0.5+ chroma → 1')
print('  0.0 = No harmonic content')
print('  0.5 = 0.25 chroma (moderate harmonic)')
print('  1.0 = 0.5+ chroma (rich harmonic)')

print('\n' + '=' * 60)
print('🎭 MOOD CLASSIFICATION RANGES')
print('=' * 60)

print('\n🔥 ENERGETIC MOOD:')
print('  Condition: tempo_score > 0.7 AND energy_score > 0.5')
print('  Translation: tempo > 98 BPM AND energy > 0.15 RMS')
print('  Characteristics: Fast tempo + High energy')
print('  Heuristic Probabilities: [calm: 0.1, energetic: 0.5, happy: 0.4, sad: 0.1]')
print('  Audio Examples: Dance, rock, electronic, upbeat pop')

print('\n😊 HAPPY MOOD (Multiple Scenarios):')
print('  ┌─ SCENARIO 1: Moderate Energy')
print('  │  Condition: tempo_score > 0.5 AND energy_score > 0.3')
print('  │  Translation: tempo > 70 BPM AND energy > 0.09 RMS')
print('  │  Probabilities: [calm: 0.2, energetic: 0.3, happy: 0.5, sad: 0.1]')
print('  │  Audio: Pop, folk, acoustic upbeat')
print('  │')
print('  ├─ SCENARIO 2: Bright & Harmonic')
print('  │  Condition: brightness_score > 0.6 AND harmonic_score > 0.5')
print('  │  Translation: brightness > 1800 Hz AND harmonic > 0.25 chroma')
print('  │  Probabilities: [calm: 0.2, energetic: 0.3, happy: 0.5, sad: 0.1]')
print('  │  Audio: Major key songs, bright instruments')
print('  │')
print('  ├─ SCENARIO 3: Low Energy (Secondary)')
print('  │  Condition: tempo_score < 0.6 AND energy_score < 0.4')
print('  │  Translation: tempo < 84 BPM AND energy < 0.12 RMS')
print('  │  Probabilities: [calm: 0.5, energetic: 0.1, happy: 0.2, sad: 0.3]')
print('  │  Audio: Gentle happy songs, lullabies')
print('  │')
print('  └─ SCENARIO 4: Balanced (Default)')
print('     Condition: All other cases')
print('     Probabilities: [calm: 0.35, energetic: 0.25, happy: 0.35, sad: 0.15]')
print('     Audio: Mixed characteristics, moderate everything')

print('\n🌊 CALM MOOD:')
print('  Condition: tempo_score < 0.6 AND energy_score < 0.4')
print('  Translation: tempo < 84 BPM AND energy < 0.12 RMS')
print('  Characteristics: Slow tempo + Low energy')
print('  Heuristic Probabilities: [calm: 0.5, energetic: 0.1, happy: 0.2, sad: 0.3]')
print('  Audio Examples: Ambient, classical, meditation, slow jazz')

print('\n😢 SAD MOOD:')
print('  Primary Condition: tempo_score < 0.6 AND energy_score < 0.4 (in calm scenario)')
print('  Translation: tempo < 84 BPM AND energy < 0.12 RMS')
print('  Characteristics: Slow tempo + Low energy (but less calm)')
print('  Heuristic Probabilities: [calm: 0.5, energetic: 0.1, happy: 0.2, sad: 0.3]')
print('  Secondary Condition: Balanced default scenario')
print('  Probabilities: [calm: 0.35, energetic: 0.25, happy: 0.35, sad: 0.15]')
print('  Audio Examples: Ballads, melancholic songs, slow minor key')

print('\n' + '=' * 60)
print('🤖 BASE ML MODEL RANGES')
print('=' * 60)

print('\n📊 VOTING CLASSIFIER OUTPUT:')
print('  Model Type: VotingClassifier (Ensemble)')
print('  Estimators: GradientBoostingClassifier + LogisticRegression')
print('  Voting: Soft probability averaging')
print('  Weights: GBC (2x) + LR (1x)')
print('  Output: 4 probability scores (sum to 1.0)')

print('\n🎯 MODEL PROBABILITY RANGES:')
print('  - Each mood: 0.0 to 1.0 (0% to 100%)')
print('  - Confidence: max(probability) × 100')
print('  - Raw model outputs before heuristics')

print('\n📈 FEATURE SPACE RANGES:')
print('  Input Features: 15 normalized audio features')
print('  Feature Scaling: StandardScaler (zero mean, unit variance)')
print('  Decision Boundaries: Complex, non-linear (GBC) + Linear (LR)')
print('  Class Separation: Multi-dimensional feature space')

print('\n' + '=' * 60)
print('🔄 FINAL PREDICTION SYSTEM')
print('=' * 60)

print('\n⚖️ THREE-LAYER SYSTEM:')
print('  1️⃣ Model Prediction: Base ML classifier output')
print('  2️⃣ Heuristic Logic: Feature-based rules (above)')
print('  3️⃣ Balanced Baseline: Equal probabilities [0.25, 0.25, 0.25, 0.25]')

print('\n🎯 DYNAMIC WEIGHTING:')
print('  - High model confidence (>0.6): Trust model more')
print('  - Low model confidence (<0.6): Trust heuristics more')
print('  - Final output: Weighted combination of all three layers')

print('\n🎵 AUDIO TO MOOD MAPPING:')
print('  ┌─ FAST + LOUD → ENERGETIC')
print('  ├─ MODERATE + BRIGHT → HAPPY')
print('  ├─ SLOW + QUIET → CALM')
print('  └─ SLOW + DARK → SAD')

print('\n📊 PROBABILITY SUMMARY TABLE:')
print('  SCENARIO           | CALM | ENERGETIC | HAPPY | SAD')
print('  ------------------|-------|-----------|-------|-----')
print('  High Energy       | 0.10  | 0.50      | 0.40  | 0.10')
print('  Moderate Energy   | 0.20  | 0.30      | 0.50  | 0.10')
print('  Low Energy        | 0.50  | 0.10      | 0.20  | 0.30')
print('  Bright Harmonic    | 0.20  | 0.30      | 0.50  | 0.10')
print('  Balanced          | 0.35  | 0.25      | 0.35  | 0.15')
print('  Baseline          | 0.25  | 0.25      | 0.25  | 0.25')

print('\n🎯 KEY THRESHOLDS SUMMARY:')
print('  TEMPO: 70 BPM (0.5), 84 BPM (0.6), 98 BPM (0.7)')
print('  ENERGY: 0.09 RMS (0.3), 0.12 RMS (0.4), 0.15 RMS (0.5)')
print('  BRIGHTNESS: 1800 Hz (0.6)')
print('  HARMONIC: 0.25 chroma (0.5)')

print('\n✅ SYSTEM COMPLETE!')
